#!/usr/bin/env bun
/**
 * ZOU-1103 (ZSF-935) — Deterministic stub scanner ahead of the consensus gate.
 *
 * The consensus panel used to pay full model cost only to discover that a
 * worker shipped a stub. This is the mechanical pre-filter: regex + AST-lite
 * over the ticket diff, no model call. Obviously-incomplete work is rejected
 * before any judge token is spent.
 *
 * Ported from the idea behind N5OS `pulse_code_validator.py`. Detects, on the
 * *added* lines of the ticket diff only:
 *   - stub-body     — a function/method/def whose sole body is bare `return`,
 *                     `pass`, or `...`
 *   - not-implemented — `NotImplementedError` / `throw new Error("not implemented")`
 *   - stub-marker   — `TODO: implement`, `STUB`, critical `FIXME`
 *   - empty-catch   — an empty (or comment-only) catch / `except: pass`
 *   - skipped-test  — `it.skip` / `describe.skip` / `test.skip` / `xit` /
 *                     `@pytest.mark.skip` introduced by the change
 *
 * Fail-open allowlist (no false positives): `.d.ts`, generated files, abstract
 * methods, and interface / overload declarations (no executable body).
 *
 * Fail-closed on detection with a specific reason string that feeds the retry
 * brief, matching how the consensus gate already reports failures.
 *
 * Advisory-first: `SF_STUB_SCAN` (off|advisory|enforce) overrides; unset
 * defaults to advisory for the first N runs (SF_STUB_SCAN_ADVISORY_RUNS,
 * default 20) then auto-enforces. `off` is byte-identical (no scan).
 *
 * The detection core (`scanDiffForStubs`) is pure — no I/O, no clock. Mode
 * resolution and the run counter live in the default outcome producer and the
 * CLI, both injectable for tests.
 *
 * CLI:
 *   bun stub-scan.ts scan --file change.diff [--mode enforce] [--json]
 *   bun stub-scan.ts scan --range origin/main...branch [--json]
 */

import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { factoryStatePath } from "./factory-state-root";

export type StubDetector =
  | "stub-body"
  | "not-implemented"
  | "stub-marker"
  | "empty-catch"
  | "skipped-test";

export interface StubFinding {
  detector: StubDetector;
  /** New-side file path (b/… without the prefix). */
  file: string;
  /** 1-based new-file line number of the offending line. */
  line: number;
  /** The offending snippet, trimmed and capped. */
  evidence: string;
  /** Human-readable explanation, surfaced in the retry brief. */
  reason: string;
}

export interface StubScanResult {
  ok: boolean;
  findings: StubFinding[];
  /** Specific reason string for the retry brief; null when ok. */
  reason: string | null;
}

export type StubScanMode = "off" | "advisory" | "enforce";

export interface StubScanOutcome {
  mode: StubScanMode;
  result: StubScanResult;
}

export interface StubScanOptions {
  /** Extra path globs (substring match) treated as generated → skipped. */
  generatedPathHints?: string[];
}

// ─── Diff model ────────────────────────────────────────────────────────────

type Language = "python" | "ts" | "other";

interface NewLine {
  /** 1-based new-file line number. */
  lineNo: number;
  /** Line text (no diff prefix). */
  text: string;
  /** True when this line was introduced by the diff (`+`), false for context. */
  added: boolean;
}

interface DiffFile {
  path: string;
  language: Language;
  /** `.d.ts` declaration file. */
  declaration: boolean;
  generated: boolean;
  /** New-side reconstruction, one entry per hunk (blocks are non-contiguous). */
  hunks: NewLine[][];
}

const EVIDENCE_CAP = 160;
const REASON_FINDINGS_CAP = 8;
const GENERATED_BANNER = /@generated|do not edit|autogenerated|auto[-\s]?generated|code generated by|generated by (?:the )?/i;
const GENERATED_PATH = /(?:^|\/)(?:dist|build|out|coverage|node_modules|__generated__|generated)\/|\.generated\.|\.gen\./;

function languageOf(path: string): Language {
  if (/\.py$/i.test(path)) return "python";
  if (/\.(?:ts|tsx|mts|cts|js|jsx|mjs|cjs)$/i.test(path)) return "ts";
  return "other";
}

/**
 * Parse a unified diff into per-file new-side reconstructions. Only files with
 * added content are returned; deletions and pure-removal files are ignored.
 * Fail-open: a malformed section is skipped rather than throwing.
 */
export function parseUnifiedDiff(diff: string): DiffFile[] {
  const files: DiffFile[] = [];
  const sections = diff.split(/(?=^diff --git )/m).filter((s) => s.trim().length > 0);
  for (const section of sections) {
    const newPathMatch = section.match(/^\+\+\+ (?:b\/)?(.+)$/m);
    if (!newPathMatch) continue;
    const path = newPathMatch[1]!.trim();
    if (path === "/dev/null") continue; // deletion

    const lines = section.split("\n");
    const hunks: NewLine[][] = [];
    let current: NewLine[] | null = null;
    let newLineNo = 0;
    for (const line of lines) {
      const hunkHeader = line.match(/^@@+ -\d+(?:,\d+)? \+(\d+)(?:,\d+)? @@/);
      if (hunkHeader) {
        current = [];
        hunks.push(current);
        newLineNo = Number(hunkHeader[1]);
        continue;
      }
      if (!current) continue;
      if (line.startsWith("+++") || line.startsWith("---")) continue;
      if (line.startsWith("+")) {
        current.push({ lineNo: newLineNo, text: line.slice(1), added: true });
        newLineNo++;
      } else if (line.startsWith("-")) {
        // removed — not part of the new side, no new-line advance
      } else if (line.startsWith(" ")) {
        current.push({ lineNo: newLineNo, text: line.slice(1), added: false });
        newLineNo++;
      }
      // Anything else — the "\ No newline" marker, a blank trailing line, or a
      // stray line between hunks — is not part of the new file body. Skip it
      // without advancing the new-file line counter. (git renders blank context
      // lines with a leading space, handled above.)
    }

    const firstAdded = hunks.flat().filter((l) => l.added).slice(0, 6).map((l) => l.text).join("\n");
    files.push({
      path,
      language: languageOf(path),
      declaration: /\.d\.ts$/i.test(path),
      generated: GENERATED_PATH.test(path) || GENERATED_BANNER.test(firstAdded),
      hunks: hunks.filter((h) => h.some((l) => l.added)),
    });
  }
  return files;
}

// ─── Line hygiene ──────────────────────────────────────────────────────────

/**
 * Strip string literals and comments so brace counting and body inspection are
 * not fooled by `{` / `}` / keywords inside strings or comments. Best-effort,
 * line-local — good enough for the tiny bodies stubs live in.
 */
function stripStringsAndComments(line: string): string {
  let out = "";
  let i = 0;
  let quote: string | null = null;
  while (i < line.length) {
    const ch = line[i]!;
    if (quote) {
      if (ch === "\\") { i += 2; continue; }
      if (ch === quote) quote = null;
      i++;
      continue;
    }
    if (ch === '"' || ch === "'" || ch === "`") { quote = ch; i++; continue; }
    if (ch === "/" && line[i + 1] === "/") break; // line comment
    if (ch === "#") break; // python comment
    if (ch === "/" && line[i + 1] === "*") { // block comment — drop to EOL, best effort
      const end = line.indexOf("*/", i + 2);
      if (end < 0) break;
      i = end + 2;
      continue;
    }
    out += ch;
    i++;
  }
  return out;
}

function commentOf(line: string): string {
  const slash = line.indexOf("//");
  const hash = line.indexOf("#");
  const block = line.indexOf("/*");
  const idx = [slash, hash, block].filter((n) => n >= 0).sort((a, b) => a - b)[0];
  return idx === undefined ? "" : line.slice(idx);
}

function indentOf(line: string): number {
  const m = line.match(/^[ \t]*/);
  return m ? m[0].replace(/\t/g, "    ").length : 0;
}

function evidence(text: string): string {
  const t = text.trim();
  return t.length > EVIDENCE_CAP ? t.slice(0, EVIDENCE_CAP - 1) + "…" : t;
}

// ─── Detectors ─────────────────────────────────────────────────────────────

const NOT_IMPLEMENTED = [
  /\bNotImplementedError\b/,
  /\bthrow\s+new\s+[A-Za-z_$][\w$]*\s*\(\s*[`'"][^`'"]*\b(?:not[\s_-]?implemented|unimplemented|not yet implemented)\b/i,
  /\braise\s+NotImplementedError\b/,
];

const SKIPPED_TEST = [
  /\b(?:it|describe|test|context|suite)\.skip\s*\(/,
  /\b(?:xit|xdescribe|xtest)\s*\(/,
  /@pytest\.mark\.skip\b/,
  /@unittest\.skip\b/,
  /\bself\.skipTest\s*\(/,
];

const SOLE_STUB_STATEMENT = /^(?:return\s*;?|pass|\.\.\.\s*;?|return\s+None\s*;?)$/;

function detectMarkers(file: DiffFile, hunk: NewLine[], out: StubFinding[]): void {
  for (const l of hunk) {
    if (!l.added) continue;
    const comment = commentOf(l.text);
    if (!comment) {
      // `throw new Error("TODO: implement")` also carries the marker in a string.
      if (!/\bTODO\b[\s:_-]*implement|\bSTUB\b/i.test(l.text)) continue;
    }
    const scope = comment || l.text;
    if (/\bTODO\b[\s:_-]*implement/i.test(scope)) {
      out.push({ detector: "stub-marker", file: file.path, line: l.lineNo, evidence: evidence(l.text), reason: "TODO: implement marker introduced by the diff" });
    } else if (/\bSTUB\b/.test(scope)) {
      out.push({ detector: "stub-marker", file: file.path, line: l.lineNo, evidence: evidence(l.text), reason: "STUB marker introduced by the diff" });
    } else if (/\bFIXME\b/.test(scope) && /\b(?:critical|urgent|blocker|p0)\b/i.test(scope)) {
      out.push({ detector: "stub-marker", file: file.path, line: l.lineNo, evidence: evidence(l.text), reason: "critical FIXME marker introduced by the diff" });
    }
  }
}

function detectNotImplemented(file: DiffFile, hunk: NewLine[], out: StubFinding[]): void {
  for (const l of hunk) {
    if (!l.added) continue;
    if (NOT_IMPLEMENTED.some((re) => re.test(l.text))) {
      out.push({ detector: "not-implemented", file: file.path, line: l.lineNo, evidence: evidence(l.text), reason: "not-implemented sentinel introduced by the diff" });
    }
  }
}

function detectSkippedTests(file: DiffFile, hunk: NewLine[], out: StubFinding[]): void {
  for (const l of hunk) {
    if (!l.added) continue;
    if (SKIPPED_TEST.some((re) => re.test(l.text))) {
      out.push({ detector: "skipped-test", file: file.path, line: l.lineNo, evidence: evidence(l.text), reason: "skipped test introduced by the diff" });
    }
  }
}

/** Match the matching `}` for the `{` first opened at or after `startIdx`. */
function matchBrace(hunk: NewLine[], startIdx: number): number {
  let depth = 0;
  let seenOpen = false;
  for (let i = startIdx; i < hunk.length; i++) {
    const code = stripStringsAndComments(hunk[i]!.text);
    for (const ch of code) {
      if (ch === "{") { depth++; seenOpen = true; }
      else if (ch === "}") { depth--; if (seenOpen && depth === 0) return i; }
    }
  }
  return -1;
}

const TS_SIGNATURE = /(?:\bfunction\b|=>|(?:^|[\s;{])(?:public|private|protected|static|async|get|set|readonly|override)\s|(?:^|[\s{;])[A-Za-z_$][\w$]*\s*\()/;

function detectStubBodiesTs(file: DiffFile, hunk: NewLine[], out: StubFinding[]): void {
  for (let i = 0; i < hunk.length; i++) {
    const raw = hunk[i]!.text;
    const code = stripStringsAndComments(raw);
    if (!code.trim().endsWith("{")) continue;
    if (!TS_SIGNATURE.test(code)) continue;
    if (/\babstract\b/.test(code)) continue; // allowlist: abstract method
    // Exclude obvious non-function blocks that also end in `{`.
    if (/\b(?:if|for|while|switch|do|try|else|catch|finally|with|interface|enum|namespace|module)\b/.test(code)) {
      if (!/\bfunction\b|=>/.test(code)) continue;
    }
    const close = matchBrace(hunk, i);
    if (close < 0 || close === i) continue;
    const bodyLines = hunk.slice(i + 1, close);
    const statements = bodyLines
      .map((l) => stripStringsAndComments(l.text).trim())
      .filter((t) => t.length > 0);
    if (statements.length !== 1) continue;
    if (!SOLE_STUB_STATEMENT.test(statements[0]!)) continue;
    const bodyAdded = bodyLines.some((l) => l.added);
    if (!bodyAdded && !hunk[i]!.added) continue;
    out.push({ detector: "stub-body", file: file.path, line: hunk[i]!.lineNo, evidence: evidence(`${raw.trim()} ${statements[0]}`), reason: `function body is only \`${statements[0]}\`` });
  }
}

const PY_DEF = /^\s*(?:async\s+)?def\s+[A-Za-z_]\w*\s*\(/;

function detectStubBodiesPy(file: DiffFile, hunk: NewLine[], out: StubFinding[]): void {
  for (let i = 0; i < hunk.length; i++) {
    const raw = hunk[i]!.text;
    if (!PY_DEF.test(raw)) continue;
    const defIndent = indentOf(raw);
    // Inline body: `def f(): pass`
    const inline = raw.match(/:\s*([^\s#][^#]*?)\s*(?:#.*)?$/);
    if (inline && !raw.trimEnd().endsWith(":")) {
      const stmt = inline[1]!.trim();
      if (SOLE_STUB_STATEMENT.test(stmt.replace(/;$/, ""))) {
        out.push({ detector: "stub-body", file: file.path, line: hunk[i]!.lineNo, evidence: evidence(raw), reason: `def body is only \`${stmt}\`` });
      }
      continue;
    }
    // Block body: collect deeper-indented lines within this hunk.
    const body: NewLine[] = [];
    for (let j = i + 1; j < hunk.length; j++) {
      const t = hunk[j]!.text;
      if (t.trim().length === 0) continue;
      if (indentOf(t) <= defIndent) break;
      body.push(hunk[j]!);
    }
    const statements = body
      .map((l) => l.text.replace(/#.*$/, "").trim())
      .filter((t) => t.length > 0);
    if (statements.length !== 1) continue;
    if (!SOLE_STUB_STATEMENT.test(statements[0]!.replace(/;$/, ""))) continue;
    if (!body.some((l) => l.added) && !hunk[i]!.added) continue;
    out.push({ detector: "stub-body", file: file.path, line: hunk[i]!.lineNo, evidence: evidence(`${raw.trim()} ${statements[0]}`), reason: `def body is only \`${statements[0]}\`` });
  }
}

function detectEmptyCatch(file: DiffFile, hunk: NewLine[], out: StubFinding[]): void {
  if (file.language === "python") {
    for (let i = 0; i < hunk.length; i++) {
      const raw = hunk[i]!.text;
      const m = raw.match(/^\s*except\b.*:\s*(?:#.*)?$/);
      if (!m) {
        // Inline `except X: pass`
        const inline = raw.match(/^\s*except\b.*:\s*(pass|\.\.\.)\s*(?:#.*)?$/);
        if (inline && hunk[i]!.added) {
          out.push({ detector: "empty-catch", file: file.path, line: hunk[i]!.lineNo, evidence: evidence(raw), reason: "empty except block introduced by the diff" });
        }
        continue;
      }
      const exceptIndent = indentOf(raw);
      const body: NewLine[] = [];
      for (let j = i + 1; j < hunk.length; j++) {
        const t = hunk[j]!.text;
        if (t.trim().length === 0) continue;
        if (indentOf(t) <= exceptIndent) break;
        body.push(hunk[j]!);
      }
      const statements = body.map((l) => l.text.replace(/#.*$/, "").trim()).filter((t) => t.length > 0);
      const onlyPass = statements.length === 1 && /^(?:pass|\.\.\.)$/.test(statements[0]!);
      if ((statements.length === 0 || onlyPass) && (body.some((l) => l.added) || hunk[i]!.added)) {
        out.push({ detector: "empty-catch", file: file.path, line: hunk[i]!.lineNo, evidence: evidence(raw), reason: "empty except block introduced by the diff" });
      }
    }
    return;
  }
  for (let i = 0; i < hunk.length; i++) {
    const code = stripStringsAndComments(hunk[i]!.text);
    if (!/\bcatch\b/.test(code)) continue;
    // Find the `{` that opens the catch body (this line or a following one).
    let openIdx = -1;
    for (let j = i; j < hunk.length && j <= i + 3; j++) {
      if (stripStringsAndComments(hunk[j]!.text).includes("{")) { openIdx = j; break; }
    }
    if (openIdx < 0) continue;
    const close = matchBrace(hunk, openIdx);
    if (close < 0) continue;
    const bodyLines = hunk.slice(openIdx + 1, close);
    const statements = bodyLines
      .map((l) => stripStringsAndComments(l.text).trim())
      .filter((t) => t.length > 0);
    if (statements.length > 0) continue;
    if (!bodyLines.some((l) => l.added) && !hunk[i]!.added) continue;
    out.push({ detector: "empty-catch", file: file.path, line: hunk[i]!.lineNo, evidence: evidence(hunk[i]!.text), reason: "empty catch block introduced by the diff" });
  }
}

// ─── Core scan ─────────────────────────────────────────────────────────────

function buildReason(findings: StubFinding[]): string {
  const head = findings.slice(0, REASON_FINDINGS_CAP)
    .map((f) => `${f.file}:${f.line} ${f.detector} (${f.reason})`)
    .join("; ");
  const more = findings.length > REASON_FINDINGS_CAP ? ` (+${findings.length - REASON_FINDINGS_CAP} more)` : "";
  return `stub scan rejected ${findings.length} finding(s): ${head}${more}`;
}

/**
 * Scan a unified diff for obviously-incomplete implementations. Pure: no I/O,
 * no clock. Deterministic — findings are ordered by (file, line, detector).
 */
export function scanDiffForStubs(diff: string, options: StubScanOptions = {}): StubScanResult {
  const hints = options.generatedPathHints ?? [];
  const files = parseUnifiedDiff(diff);
  const findings: StubFinding[] = [];
  for (const file of files) {
    if (file.declaration) continue;                                   // allowlist: .d.ts
    if (file.generated || hints.some((h) => file.path.includes(h))) continue; // allowlist: generated
    for (const hunk of file.hunks) {
      detectMarkers(file, hunk, findings);
      detectNotImplemented(file, hunk, findings);
      detectSkippedTests(file, hunk, findings);
      detectEmptyCatch(file, hunk, findings);
      if (file.language === "python") detectStubBodiesPy(file, hunk, findings);
      else if (file.language === "ts") detectStubBodiesTs(file, hunk, findings);
    }
  }
  findings.sort((a, b) =>
    a.file.localeCompare(b.file) || a.line - b.line || a.detector.localeCompare(b.detector)
  );
  const ok = findings.length === 0;
  return { ok, findings, reason: ok ? null : buildReason(findings) };
}

// ─── Mode resolution + run counter ───────────────────────────────────────────

export const DEFAULT_ADVISORY_RUNS = 20;
const COUNTER_FILE = "stub-scan-runs.json";

/** Lazily resolved so import alone never requires FACTORY_STATE_DIR. */
function defaultStateDir(): string {
  return factoryStatePath("stub-scan");
}

export interface ModeInput {
  /** Value of SF_STUB_SCAN, if set. */
  env?: string;
  /** How many enforced-eligible runs have already happened. */
  runCount: number;
  /** Advisory-run threshold before auto-enforce. */
  advisoryRuns?: number;
}

/**
 * Resolve the effective scan mode. Env override wins; otherwise advisory for
 * the first `advisoryRuns` runs, then enforce. Pure.
 */
export function resolveScanMode(input: ModeInput): StubScanMode {
  const env = (input.env ?? "").trim().toLowerCase();
  if (env === "off" || env === "0" || env === "false") return "off";
  if (env === "advisory" || env === "shadow" || env === "log-only") return "advisory";
  if (env === "enforce" || env === "on" || env === "1" || env === "true") return "enforce";
  const threshold = input.advisoryRuns ?? DEFAULT_ADVISORY_RUNS;
  return input.runCount >= threshold ? "enforce" : "advisory";
}

function readRunCount(stateDir: string): number {
  try {
    const p = join(stateDir, COUNTER_FILE);
    if (!existsSync(p)) return 0;
    const parsed = JSON.parse(readFileSync(p, "utf8")) as { count?: unknown };
    return typeof parsed.count === "number" && parsed.count >= 0 ? Math.floor(parsed.count) : 0;
  } catch {
    return 0; // fail-open — a corrupt counter defaults to advisory
  }
}

function bumpRunCount(stateDir: string, next: number): void {
  try {
    if (!existsSync(stateDir)) mkdirSync(stateDir, { recursive: true });
    writeFileSync(join(stateDir, COUNTER_FILE), JSON.stringify({ count: next }) + "\n");
  } catch {
    // counter is best-effort; never block a scan on it
  }
}

/**
 * Produce a scan outcome for the consensus gate: resolve the mode from the
 * environment + persisted run counter, run the pure scan, and (when not off)
 * increment the counter so the advisory window advances. This is the default
 * `scanForStubs` dependency; tests inject a pure stand-in instead.
 */
export function defaultStubScanOutcome(
  diff: string,
  opts: { stateDir?: string; env?: NodeJS.ProcessEnv; options?: StubScanOptions } = {},
): StubScanOutcome {
  const stateDir = opts.stateDir ?? defaultStateDir();
  const env = opts.env ?? process.env;
  const runCount = readRunCount(stateDir);
  const mode = resolveScanMode({
    env: env.SF_STUB_SCAN,
    runCount,
    advisoryRuns: env.SF_STUB_SCAN_ADVISORY_RUNS ? Number(env.SF_STUB_SCAN_ADVISORY_RUNS) : undefined,
  });
  if (mode === "off") {
    return { mode, result: { ok: true, findings: [], reason: null } };
  }
  const result = scanDiffForStubs(diff, opts.options);
  bumpRunCount(stateDir, runCount + 1);
  return { mode, result };
}

// ─── CLI ─────────────────────────────────────────────────────────────────────

function readDiffFromRange(range: string): string {
  const result = Bun.spawnSync(["git", "diff", "--no-ext-diff", "--find-renames", range], {
    stdout: "pipe",
    stderr: "pipe",
  });
  if (result.exitCode !== 0) {
    throw new Error(result.stderr.toString().trim() || `git diff ${range} failed`);
  }
  return result.stdout.toString();
}

function parseArgs(argv: string[]): Map<string, string | boolean> {
  const args = new Map<string, string | boolean>();
  for (let i = 0; i < argv.length; i++) {
    const a = argv[i]!;
    if (!a.startsWith("--")) continue;
    const key = a.slice(2);
    const next = argv[i + 1];
    if (next && !next.startsWith("--")) { args.set(key, next); i++; }
    else args.set(key, true);
  }
  return args;
}

function fail(msg: string): never {
  console.error(`[stub-scan] ${msg}`);
  process.exit(2);
}

async function main(argv: string[]): Promise<void> {
  const command = argv[0];
  if (command !== "scan") {
    fail(`unknown command "${command ?? ""}" — usage: stub-scan.ts scan (--file <diff> | --range <a...b>) [--mode off|advisory|enforce] [--json]`);
  }
  const args = parseArgs(argv.slice(1));
  const file = args.get("file");
  const range = args.get("range");
  let diff: string;
  if (typeof file === "string") {
    if (!existsSync(file)) fail(`diff file not found: ${file}`);
    diff = readFileSync(file, "utf8");
  } else if (typeof range === "string") {
    diff = readDiffFromRange(range);
  } else {
    fail("provide --file <diff> or --range <a...b>");
  }

  const modeArg = args.get("mode");
  const env = { ...process.env };
  if (typeof modeArg === "string") env.SF_STUB_SCAN = modeArg;
  const outcome = defaultStubScanOutcome(diff!, { env });

  if (args.get("json")) {
    console.log(JSON.stringify(outcome));
  } else if (outcome.result.ok) {
    console.error(`[stub-scan] ${outcome.mode}: clean — no stubs detected`);
  } else {
    console.error(`[stub-scan] ${outcome.mode}: ${outcome.result.reason}`);
    for (const f of outcome.result.findings) {
      console.error(`  - ${f.file}:${f.line} [${f.detector}] ${f.reason} :: ${f.evidence}`);
    }
  }

  // Enforce → non-zero on detection; advisory/off are log-only.
  if (outcome.mode === "enforce" && !outcome.result.ok) process.exit(1);
  process.exit(0);
}

if (import.meta.main) {
  main(process.argv.slice(2)).catch((err) => fail(err instanceof Error ? err.message : String(err)));
}
