/**
 * Seed specification generator for prescriptions
 */

import { randomUUID } from 'crypto';
import type { Playbook, MetricResult } from '../types.js';

export function generateSeed(playbook: Playbook, metric: MetricResult): string {
  const id = `seed-${randomUUID().slice(0, 8)}`;
  const now = new Date().toISOString();

  return `# Seed Specification
# Generated: ${now}
# ID: ${id}
# Source: Zouroboros Self-Heal Prescription

id: "${id}"
created: "${now}"
status: draft

goal: "Improve ${metric.name} from ${(metric.value * 100).toFixed(1)}% to ${(metric.target * 100).toFixed(0)}%"

constraints:
${playbook.constraints.map(c => `  - "${c}"`).join('\n')}

acceptance_criteria:
  - "${metric.name} >= ${(metric.target * 100).toFixed(0)}%"
  - "All existing tests pass"
  - "No regressions in other metrics"

ontology:
  name: "improvement"
  description: "Self-healing improvement cycle"
  fields:
    - name: metric
      type: string
      description: "Name of metric being improved"
    - name: baseline
      type: number
      description: "Starting value"
    - name: target
      type: number
      description: "Goal value"

evaluation_principles:
  - name: correctness
    description: "Does the fix address the root cause?"
    weight: 0.4
  - name: safety
    description: "Does it preserve existing functionality?"
    weight: 0.3
  - name: completeness
    description: "Are all acceptance criteria met?"
    weight: 0.3

exit_conditions:
  - name: target_met
    description: "Metric reaches target"
    criteria: "${metric.name} >= ${metric.target}"
  - name: regression_detected
    description: "Any metric drops below critical"
    criteria: "Any metric < critical threshold"
  - name: max_experiments
    description: "Maximum experiments reached"
    criteria: "Experiment count >= 50"
`;
}

export function generateProgram(playbook: Playbook, metric: MetricResult): string | null {
  if (!playbook.targetFile) {
    return null; // Script mode - no autoloop needed
  }

  return `# Program: ${playbook.name}

## Objective

Improve ${metric.name} from ${(metric.value * 100).toFixed(1)}% to ${(metric.target * 100).toFixed(0)}%.

## Metric

- **Name**: ${playbook.id}-metric
- **Direction**: ${playbook.metricDirection}
- **Command**: \`${playbook.metricCommand}\`

## Setup

\`\`\`bash
${playbook.setupCommands?.join('\n') || '# No setup required'}
\`\`\`

## Target File

${playbook.targetFile}

## Run Command

\`\`\`bash
${playbook.runCommand || `bun ${playbook.targetFile.replace('.ts', '.ts')}`}
\`\`\`

## Read-Only Files

${playbook.readOnlyFiles?.map(f => `- ${f}`).join('\n') || '# None specified'}

## Constraints

${playbook.constraints.map(c => `- ${c}`).join('\n')}

## Stagnation

- Threshold: 10 experiments without improvement
- Double threshold: 20 experiments
- Triple threshold: 30 experiments

## Notes

Generated by Zouroboros Self-Heal.
Do not manually edit this file.
`;
}