/**
 * draft.ts — produce a candidate skill scaffold from a Candidate cluster.
 *
 * Output shape:
 *   <slugDir>/
 *     SKILL.md              ← LLM-drafted (workload: summarization)
 *     scripts/<step>.ts     ← TODO-stub mirroring trace tool calls
 *
 * Hybrid policy (per seed): SKILL.md is LLM-authored prose only; scripts are
 * mechanical stubs derived from the recorded trace. The LLM never authors
 * executable logic in v1.
 *
 * Cost: every LLM call increments the per-run llm_cost_usd accumulator. The
 * caller is responsible for enforcing $0.10/run + $1/day caps before invoking
 * us; we just report what we spent.
 */

import { Candidate, SourceRow } from './types.js';
import { slugify } from './slug.js';

export interface DraftedFile {
  /** Relative path within the candidate slug directory. */
  path: string;
  content: string;
}

export interface DraftedSkill {
  slug: string;
  files: DraftedFile[];
  /** Sum of LLM cost incurred drafting this candidate (USD). */
  llm_cost_usd: number;
}

export interface DraftOptions {
  /** Pre-resolved slug (caller has run validateSlug + collision check). */
  slug: string;
  /**
   * Tool calls extracted from the recorded trace; one stub script per unique
   * tool. If empty, no scripts are written (SKILL.md only) — caller decides
   * whether to fail eval.
   */
  toolCalls: TraceToolCall[];
  /**
   * Pluggable LLM driver. PR1 ships no default — the CLI in PR3 will wire
   * `packages/memory/src/standalone/model-client.ts:generate` (workload
   * 'summarization', gpt-4o-mini per memory-model-migration). Tests inject a
   * stub returning canned content.
   */
  llm: LlmDriver;
}

export interface TraceToolCall {
  /** Tool name as recorded — e.g. `Read`, `Bash`, `mcp__zo__send_email_to_user`. */
  tool: string;
  /** First-seen sample arguments (rendered as a JSON comment in the stub). */
  sample_args?: Record<string, unknown>;
}

export type LlmDriver = (prompt: string) => Promise<{
  content: string;
  cost_usd: number;
}>;

/**
 * System prompt the CLI passes through to the LLM driver in PR3. Exposed as
 * a const so the system-message text can be unit-asserted (FX-related
 * mutation gate: production drafts must explicitly forbid shell snippets).
 */
export const SKILL_MD_SYSTEM = `You write SKILL.md files that summarize a successful
recurring task pattern. The file you produce is *prose only* — no code blocks
that look executable, no shell commands, no install instructions, no curl/wget
references. Stay descriptive and short. The reader is an agent looking for a
skill to invoke; they need to know *what* the pattern does and *when* to invoke
it, not how it's implemented (the scripts/ folder handles that).`;

function buildPrompt(slug: string, sources: SourceRow[]): string {
  const samples = sources
    .slice(0, 8)
    .map((s, i) => {
      switch (s.kind) {
        case 'procedure':
          return `${i + 1}. procedure "${s.name}" (success_count=${s.success_count})`;
        case 'episode':
          return `${i + 1}. episode "${s.summary}" (outcome=${s.outcome})`;
        case 'skill_execution':
          return `${i + 1}. skill "${s.skill_name}" (outcome=${s.outcome})`;
      }
    })
    .join('\n');

  return `Slug: ${slug}

Source patterns (a successful recurring task this skill should encapsulate):
${samples}

Produce a SKILL.md with this exact structure:
---
name: ${slug}
description: <one sentence — under 30 words, what this skill does>
---

# ${slug}

## When to invoke
- <bullet 1>
- <bullet 2>

## Inputs
- <bullet>

## Outputs
- <bullet>

Do NOT include shell commands, install instructions, or executable snippets.`;
}

function stubFor(tool: TraceToolCall): DraftedFile {
  const safeName = slugify(tool.tool) || 'step';
  const argSample = tool.sample_args
    ? `// sample args: ${JSON.stringify(tool.sample_args).slice(0, 240)}`
    : '// sample args: <none recorded>';
  return {
    path: `scripts/${safeName}.ts`,
    content: `// TODO(${tool.tool}): implement step.
// This stub was generated by skill-crystallization-v1 from a recorded trace.
// The crystallizer never writes executable logic — fill it in by hand.
${argSample}

export async function run(): Promise<void> {
  throw new Error('TODO: implement ${tool.tool} step');
}
`,
  };
}

export async function draftCandidate(
  candidate: Candidate,
  opts: DraftOptions,
): Promise<DraftedSkill> {
  const prompt = buildPrompt(opts.slug, candidate.sources);
  const { content: skillMd, cost_usd } = await opts.llm(prompt);

  const files: DraftedFile[] = [{ path: 'SKILL.md', content: skillMd }];
  for (const call of opts.toolCalls) {
    files.push(stubFor(call));
  }

  return {
    slug: opts.slug,
    files,
    llm_cost_usd: cost_usd,
  };
}
